# Generated by Django 2.2.1 on 2019-05-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=3, max_digits=6)),
                ('radius', models.DecimalField(decimal_places=3, max_digits=19)),
            ],
        ),
    ]
