version: '3'

services:
  web:
    build: .
    command: gunicorn bbgraph.wsgi:application -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  celery:
    build: .
    command: ['celery', '-A', 'bbgraph', 'worker', '-l', 'INFO']
    volumes:
      - .:/code
      - ./static:/static

    depends_on:
      - redis

  redis:
    image: redis:3.2.11


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - web
